version: "3"

# Complementary services, not part of geOrchestra core.
# They are made to ease your life as a developer.
# **NOT** production ready !

volumes:
  smtp_maildir:
networks:
  proxy:
    external: true
  traefik:
    external: true

services:
  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sp"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org"
      - "traefik.frontend.passHostHeader=true"

  cas:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cas"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org;PathPrefix:/cas"

  smtp:
    image: camptocamp/smtp-sink:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/

  courier-imap:
    image: camptocamp/courier-imap:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/

  webmail:
    image: camptocamp/sqwebmail:latest
    environment:
      - IMAP_HOSTNAME=courier-imap
      - SMTP_HOSTNAME=smtp-sink
    volumes:
      - smtp_maildir:/home/smtp/Maildir/
    labels:
      - "traefik.enable=true"
      - "traefik.backend=webmail"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org;PathPrefix:/webmail"

  ssh:
    image: georchestra/ssh_data:latest
    ports:
      - "2222:22"
    volumes:
      - geoserver_geodata:/mnt/geoserver_geodata
